language: cpp

# Need these for a more recent CMake on Linux
sudo: required
dist: trusty

os:
  - osx
  - linux

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - cmake --build .

after_script:
 - cmake --build . --target tests
